#!/bin/bash

update_anarchy() {
  echo "Updating Anarchy..."
  dotfiles="$HOME/.config/anarchy/dots"
  cd "$dotfiles"

  git pull --rebase --autostash

  cd "$dotfiles/home"
  stow -R -t "$HOME" .

  hyprctl reload 2>/dev/null || true

  pkill qs
  qs &
}

case "$1" in
  update)
    update_anarchy;;
  *)
    echo "Unknown arguments";;
esac
